import type { RegistryEntry } from "../../../shared.ts";

export const perplexityAgentProvider: RegistryEntry = {
  id: "perplexity-agent",
  alias: "pplx-agent",
  format: "openai-responses",
  executor: "default",
  baseUrl: "https://api.perplexity.ai/v1/responses",
  modelsUrl: "https://api.perplexity.ai/v1/models",
  testKeyModelsUrl: "https://api.perplexity.ai/v1/models",
  authType: "apikey",
  authHeader: "bearer",
  passthroughModels: true,
  liveCatalogAuthoritative: false,
  models: [
    // Keep these IDs aligned with https://docs.perplexity.ai/docs/agent-api/models.
    // Perplexity exposes some third-party families through the `perplexity/` prefix.
    { id: "anthropic/claude-fable-5", name: "Claude Fable 5 (Perplexity Agent)" },
    { id: "anthropic/claude-opus-5", name: "Claude Opus 5 (Perplexity Agent)" },
    { id: "anthropic/claude-opus-4-8", name: "Claude Opus 4.8 (Perplexity Agent)" },
    { id: "anthropic/claude-opus-4-7", name: "Claude Opus 4.7 (Perplexity Agent)" },
    { id: "anthropic/claude-opus-4-6", name: "Claude Opus 4.6 (Perplexity Agent)" },
    { id: "anthropic/claude-opus-4-5", name: "Claude Opus 4.5 (Perplexity Agent)" },
    { id: "anthropic/claude-sonnet-5", name: "Claude Sonnet 5 (Perplexity Agent)" },
    { id: "anthropic/claude-sonnet-4-6", name: "Claude Sonnet 4.6 (Perplexity Agent)" },
    { id: "anthropic/claude-sonnet-4-5", name: "Claude Sonnet 4.5 (Perplexity Agent)" },
    { id: "anthropic/claude-haiku-4-5", name: "Claude Haiku 4.5 (Perplexity Agent)" },
    {
      id: "openai/gpt-5.6-sol",
      name: "GPT-5.6 Sol (Perplexity Agent)",
      supportsReasoning: true,
      toolCalling: true,
    },
    { id: "openai/gpt-5.6-terra", name: "GPT-5.6 Terra (Perplexity Agent)" },
    { id: "openai/gpt-5.6-luna", name: "GPT-5.6 Luna (Perplexity Agent)" },
    { id: "openai/gpt-5.5", name: "GPT-5.5 (Perplexity Agent)" },
    { id: "openai/gpt-5.4", name: "GPT-5.4 (Perplexity Agent)" },
    { id: "openai/gpt-5.4-mini", name: "GPT-5.4 Mini (Perplexity Agent)" },
    { id: "openai/gpt-5.4-nano", name: "GPT-5.4 Nano (Perplexity Agent)" },
    { id: "openai/gpt-5.2", name: "GPT-5.2 (Perplexity Agent)" },
    { id: "openai/gpt-5.1", name: "GPT-5.1 (Perplexity Agent)" },
    { id: "openai/gpt-5", name: "GPT-5 (Perplexity Agent)" },
    { id: "openai/gpt-5-mini", name: "GPT-5 Mini (Perplexity Agent)" },
    { id: "google/gemini-3.1-pro-preview", name: "Gemini 3.1 Pro Preview (Perplexity Agent)" },
    { id: "google/gemini-3.1-flash-lite", name: "Gemini 3.1 Flash Lite (Perplexity Agent)" },
    { id: "google/gemini-3.5-flash", name: "Gemini 3.5 Flash (Perplexity Agent)" },
    { id: "google/gemini-3.5-flash-lite", name: "Gemini 3.5 Flash Lite (Perplexity Agent)" },
    { id: "google/gemini-3.6-flash", name: "Gemini 3.6 Flash (Perplexity Agent)" },
    { id: "google/gemini-3.7-flash", name: "Gemini 3.7 Flash (Perplexity Agent)" },
    { id: "google/gemini-3-flash-preview", name: "Gemini 3.0 Flash Preview (Perplexity Agent)" },
    { id: "xai/grok-4.6", name: "Grok 4.6 (Perplexity Agent)" },
    { id: "xai/grok-4.5", name: "Grok 4.5 (Perplexity Agent)" },
    { id: "xai/grok-4.3", name: "Grok 4.3 (Perplexity Agent)" },
    {
      id: "xai/grok-4.20-reasoning",
      name: "Grok 4.20 Reasoning (Perplexity Agent)",
      supportsReasoning: true,
    },
    { id: "xai/grok-4.20-non-reasoning", name: "Grok 4.20 Non Reasoning (Perplexity Agent)" },
    { id: "xai/grok-4.20-multi-agent", name: "Grok 4.20 Multi-Agent (Perplexity Agent)" },
    { id: "perplexity/deepseek-v4-flash-0731", name: "DeepSeek V4 Flash 0731 (Perplexity Agent)" },
    { id: "perplexity/glm-5.2", name: "GLM 5.2 (Perplexity Agent)" },
    { id: "perplexity/glm-5.3", name: "GLM 5.3 (Perplexity Agent)" },
    {
      id: "perplexity/kimi-k3",
      name: "Kimi K3 (Perplexity Agent)",
      supportsReasoning: true,
      supportedThinkingEfforts: ["minimal", "low", "medium", "high", "xhigh", "max"],
    },
    { id: "perplexity/kimi-k2.7-code", name: "Kimi K2.7 Code (Perplexity Agent)" },
    {
      id: "perplexity/nemotron-3.5-lightning-30b-a3b",
      name: "Nemotron 3.5 Lightning 30B A3B (Perplexity Agent)",
    },
    {
      id: "perplexity/nemotron-3-ultra-550b-a55b",
      name: "Nemotron 3 Ultra 550B A55B (Perplexity Agent)",
    },
    { id: "perplexity/sonar", name: "Sonar (Perplexity Agent)" },
  ],
};
